version: '2'

services:
  slapcountdown-frontend:
    image: superbuddy/ng-cli-nginx
    env_file: 
      - .env
    ports:
      - "${EXPOSED_FRONTEND_DEV_PORT}:4200"
      - 49152:49152
      - "${EXPOSED_FRONTEND_PROD_PORT}:80"
    environment:
      - "VIRTUAL_HOST=${LETSENCRYPT_HOST_FRONTEND}"
      - VIRTUAL_NETWORK=nginx-proxy
      - "VIRTUAL_PORT=${LETSENCRYPT_PORT_FRONTEND}"
      - "LETSENCRYPT_HOST=${LETSENCRYPT_HOST_FRONTEND}"
      - "LETSENCRYPT_EMAIL=${LETSENCRYPT_MAIL}"
    volumes:
      - /var/log/docker/slapcountdown_frontend:/var/log
      - "${PATH_TO_FRONTEND}:/project"
      - "${PATH_TO_SDK}:/project/src/app/sdk"
    networks:
      - slapcountdown
      - proxy-tier

  slapcountdown-backend:
    image: superbuddy/loopback-sdk-builder
    env_file: 
      - .env
    ports:
      - "${EXPOSED_BACKEND_PORT}:3000"
      - "${EXPOSED_BACKEND_DEBUGGER}:5858"
    environment:
      - "VIRTUAL_HOST=${LETSENCRYPT_HOST_BACKEND}"
      - VIRTUAL_NETWORK=nginx-proxy
      - "VIRTUAL_PORT=${LETSENCRYPT_PORT_BACKEND}"
      - "LETSENCRYPT_HOST=${LETSENCRYPT_HOST_BACKEND}"
      - "LETSENCRYPT_EMAIL=${LETSENCRYPT_MAIL}"
    volumes:
      - /var/log/docker/slapcountdown_backend:/var/log
      - "${PATH_TO_BACKEND}:/project"
      - "${PATH_TO_SDK}:/sdk"
    networks:
      - slapcountdown
      - proxy-tier
      
  slapcountdown-database:
    image: tutum/mongodb:3.2
    ports:
      - "27017:27017"
      - "28017"
    env_file: 
      - .env
    environment:
      - "MONGODB_USER=${MONGODB_USER}"
      - "MONGODB_DATABASE=${MONGODB_DATABASE}"
      - "MONGODB_PASS=${MONGODB_PASS}"
    networks:
      - slapcountdown
      
networks:
  proxy-tier:
    external:
      name: nginx-proxy
  slapcountdown:
    external:
      name: slapcountdown